# Generated by Django 3.0.2 on 2020-02-02 18:34

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', multiselectfield.db.fields.MultiSelectField(choices=[('Java', 'Java'), ('C++', 'C++'), ('C', 'C'), ('Python', 'Python')], max_length=17)),
                ('experience', models.IntegerField()),
                ('notice_period', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('max_salary', models.FloatField()),
                ('negotiable', models.BooleanField(default=False)),
            ],
        ),
    ]
